name: Nimbus 26 ì¬ê³  ì…ê³  ì•Œë¦¼! ğŸ””

on:
  push:
    branches:
      - main
    paths:
      - 'stock_log.txt'

jobs:
  notify-on-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Send a notification
        run: echo "ì¬ê³  ì…ê³ ê°€ í™•ì¸ë˜ì—ˆìŠµë‹ˆë‹¤! ê¹ƒí—ˆë¸Œ ì•±ìœ¼ë¡œ ì•Œë¦¼ì´ ê°ˆ ê±°ì˜ˆìš”."
